services:
  api:
    build: .
    container_name: simple-image-storage
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data"
    environment:
      SIS_ACCESS_TOKEN: ""
      SIS_LOG_LEVEL: "ERROR"
